#version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test:api-all #test:localization
    volumes:
      #- ./playwright-report/:/app/playwright-report
      - .:/app/playwright-report
      - ./test-results/:/app/test-results
