name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  job1:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Delete existing index.html file
        run: rm -f index.html # Remove index.html if it exists

      - name: Run Playwright tests
        run: |
          docker-compose up --build -d
      #- name: Wait for containers to finish
      #  run: |
      #    timeout 10m sh -c 'until docker-compose logs --tail=1 | grep "Test run complete"; do sleep 10; done'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/checkout@v4
      - name: Replace the report file with the newly generated one
        run: yes | cp -rf playwright-report/index.html .
      - name: Commit files # commit the report
        run: |
          git config --local user.email "hristovatonika@gmail.com"
          git config --local user.name "GitHub Action test"
          git add .
          git commit -m "Add report"
      - name: Push changes # push the output folder to your repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force
  deploy:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4
      - name: Copy index.html to root directory
        run: |
          cp index.html ./index.html
      - name: Commit and push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "hristovatonika@gmail.com"
          git config --local user.name "GitHub Action test"
          git add index.html
          git commit -m "Deploy HTML report to main branch"
          git push origin main
